Dungeons/Controllers/CharacterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Dungeons.Data;
using Dungeons.Models;

namespace Dungeons.Controllers
{
    public class CharacterController : Controller
    {
        public ICharacterDataAccess _database { get; set; }

        public CharacterController(ICharacterDataAccess database)
        {
            _database = database;
        }

        // GET: Character
        public async Task<IActionResult> Index(int userId)
        {
            return View(await _database.GetMyCharacterListAsync(userId));
        }

        // GET: Character/DisplayCharacter/5
        public async Task<IActionResult> DisplayCharacter(string code)
        {
            if (code == null)
            {
                return NotFound();
            }

            var character = await _database.GetCharacterByCode(code);

            if (character == null)
            {
                return NotFound();
            }

            return View(character);
        }

        // GET: Character/CreateCharacter
        public IActionResult CreateCharacter()
        {
            return View();
        }

        // POST: Character/CreateCharacter
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreateCharacter([Bind("Character_ID,User_ID,Code,Name,Alignment,Experience,Level,RaceName,ClassName,MaxHealth,CurrentHealth,Strength,Dexterity,Constitution,Intelligence,Wisdom,Charisma,SavingThrows,Proficiencies,Languages")] Character character)
        {
            if (ModelState.IsValid)
            {
                await _database.CreateCharacter(character);
                return RedirectToAction(nameof(Index));
            }
            return View(character);
        }

        // GET: Character/EditCharacter/5
        public async Task<IActionResult> UpdateCharacter(string code)
        {
            if (code == null)
            {
                return NotFound();
            }

            var character = await _database.GetCharacterByCode(code);

            if (character == null)
            {
                return NotFound();
            }
            return View(character);
        }

        // POST: Character/EditCharacter/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateCharacter(string code, [Bind("Code,User_ID,Name,Alignment,Experience,Level,RaceName,ClassName,MaxHealth,CurrentHealth,Strength,Dexterity,Constitution,Intelligence,Wisdom,Charisma,SavingThrows,Proficiencies,Languages")] Character character)
        {
            if (code != character.Code)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _database.UpdateCharacter(character);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CharacterExists(character.Code))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(character);
        }

        // GET: Character/EditCharacterBag
        public async Task<IActionResult> UpdateCharacterBag(string code)
        {
            if (code == null)
            {
                return NotFound();
            }

            var character = await _database.GetCharacterBagByCode(code);

            if (character == null)
            {
                return NotFound();
            }
            return View(character);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateCharacterBag(string code, [Bind("CharacterCode,ItemList,Gold,Silver,Copper")] CharacterBag bag)
        {
            if (code != bag.CharacterCode)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _database.UpdateCharacterBag(bag);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CharacterBagExists(bag.CharacterCode))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(bag);
        }

        public async Task<IActionResult> UpdateCharacterEquipped(string code)
        {
            if (code == null)
            {
                return NotFound();
            }

            var character = await _database.GetCharacterEquippedByCode(code);

            if (character == null)
            {
                return NotFound();
            }
            return View(character);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateCharacterEquipped(string code, [Bind("CharacterCode,SpecialItems,ArmourClass,ArmourName,MainHand,OffHand")] CharacterEquipped equipped)
        {
            if (code != equipped.CharacterCode)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    await _database.UpdateCharacterEquipped(equipped);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CharacterEquippedExists(equipped.CharacterCode))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(equipped);
        }

        // GET: Character/DeleteCharacter/5
        public async Task<IActionResult> DeleteCharacter(string code)
        {
            if (code == null)
            {
                return NotFound();
            }

            var character = await _database.GetCharacterByCode(code);

            if (character == null)
            {
                return NotFound();
            }

            return View(character);
        }

        // POST: Character/DeleteCharacter/
        [HttpPost, ActionName("DeleteCharacter")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteCharacterConfirmed(string code)
        {
            await _database.DeleteCharacter(code);
            //await _database.DeleteCharacterBag(code);
            //await _database.DeleteCharacterEquipped(code);

            return RedirectToAction(nameof(Index));
        }

        private bool CharacterExists(string code)
        {
            try
            {
                if (_database.GetCharacterByCode(code) != null)
                {
                    return true;
                }

            }
            catch
            {
                throw;
            }

            return false;
        }

        private bool CharacterBagExists(string code)
        {
            try
            {
                if (_database.GetCharacterBagByCode(code) != null)
                {
                    return true;
                }

            }
            catch
            {
                throw;
            }

            return false;
        }
        private bool CharacterEquippedExists(string code)
        {
            try
            {
                if (_database.GetCharacterEquippedByCode(code) != null)
                {
                    return true;
                }

            }
            catch
            {
                throw;
            }

            return false;
        }
    }
}

Dungeons/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Dungeons</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/custom.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <a asp-controller="Home" asp-action="Index"><img src="images/Dungeons.png"></a>

            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Dungeons</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Character" asp-action="CreateCharacter">Create Character</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Dungeons - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @* TO BE REMOVED - TEST PURPOSES ONLY *@
    <script src="~/js/app.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>